### ISSUE TITLE
zscore tests fail from time to time

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#105]
The zscore, zscore out and zscore in test fail for Binary Undirected sometimes.

**Comment by AdamLiberda** [comment]
I think this might have something to do with the community structure. That it finds different ones on different runs. I had a similar problem for participation

**Comment by giovannivolpe** [comment]
This is not a problem. There are several measures that will be different for different runs. You can assign the community structure for the test runs.
