### ISSUE TITLE
Test function of randomize validity

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#148]
See pseudo-code below. Write test_randomization function. Should be robust

A pseudo-code for the analysis could be the following 
`gm_new = test_randomization(A, type, randomize_function_new, n_randomizations)`
`gm_old = test_randomization(A, type, randomize_function_old, n_randomizations)`
`valid = compare_two_methods(gm_new, gm_old) %statistical comparision`
`save_validation(valid)`
`save_global_measures(gm_new, gm_old) % Save so we can plot them etc after`

`function gm_list = test_randomization(A, type, randomize_function, n_randomizations)`
`for i = 1:n_randomizations`
     `rA = randomize_function(A)`
     `gm = calculate_global_measures(A, type)`
    `add_measure_to_list_of_measures(gm)`
`return list_of_all_global_measures`

**Comment by giovannivolpe** [comment]
Yes, it makes sense

**Comment by AdamLiberda** [comment]
Merged into develop. Closing
