### ISSUE TITLE
Kolmogorov-Smirnov test

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#150]
Implement a function for performing the [Kolmogorov-Smirnov ](https://en.wikipedia.org/wiki/Kolmogorov–Smirnov_test) test of distributions. Should take two sets of data and a confidence level(if it's needed for the test) and return true if the two sets of data are from the same distribution.

**Comment by AdamLiberda** [comment]
Merged into develop. Closing
