### ISSUE TITLE
Standard matrices

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#151]
Create a set of standard matrices of different densities which can be used to test the validity of randomize functions

**Comment by TheoBerglin** [comment]
Also, create a set of standard matrices of different size for test of time complexity of the randomization methods

**Comment by TheoBerglin** [comment]
Still need to create weighted graphs. Keep open

**Comment by AdamLiberda** [comment]
Matrices for 100 nodes BD, BU, WD, WU done.
Matrices for 1000 nodes BD, BU, WD, WU done.
