### ISSUE TITLE
Test pipeline

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#165]
Run a test. Upload the .mat files to github so they can be used for Ground truth. Continue with next test.
We can do this issue after #164 and #151.

**Test of validity test** 
- [x] BCT_BD against BCT_BD Theo
- [x] BCT_BU against BCT_BU Theo 
- [x] BCT_WD against BCT_WD
- [x] BCT_WU against BCT_WU

**Test Giovanni**
- [x] GiovanniBD original against BCT_BD Adam - fail for dens 0.7 (rand, str, deg)
- [x] GiovanniBD fix against BCT_BD Adam
- [x] GiovanniBU original against BCT_BU Adam - fail for dens 0.7 (str, deg)
- [x] GiovanniBU fix against BCT_BU Adam
- [x] Gio_bct_WD against BCT_WD - Fail for dens 0.6 - 0.7 due to miswires
- [x] Gio_bct_fix_WD against BCT_WD
- [x] Gio_bct_WU against BCT_WU - Fail for dens 0.7 due to miswires
- [x] Gio_bct_fix_WU against BCT_WU

**Comment by TheoBerglin** [comment]
I've added so that the diagnoal is removed prior to randomization and added after randomization. This yields that 16/28 measures distributions pass the Kolmogorov-Smirnov test. The test that doesn't pass are:
assortativity_in_in
assortativity_in_in_in_out
assortativity_in_in_out_in
assortativity_in_in_out_out
cpl
cpl_in
cpl_out
clustering_global
gleff_av
gleff_in_av
gleff_out_av
leff_av

**Comment by AdamLiberda** [comment]
The BraphBD scores 27/28 for 3 different densities and for 3 different measures, otherwise 28/28 The ones that fail are:
dens 0.25 - clustering
dens 0.35 - local efficiency
dens 0.45 - assortativity-in-in

**Comment by giovannivolpe** [comment]
Note that the randomisation methods I implemented might lead to slightly different degree distributions (because they might not be able to assign 2-3 edges). In practice, this should not be a problem for large matrices.

**Comment by TheoBerglin** [comment]
I see, the BU method you implemented passes the degree-distribution if we remove the diagonal prior to randomization and add it again after randomization for graphs of size 100. I'll test with a graph of fewer nodes tomorrow

**Comment by TheoBerglin** [comment]
I ran the bu method for matrices of lower densities and the lower the densities the more distribtuions fail.

**Comment by TheoBerglin** [comment]
The current implementation of randomize for BU in braph is incorrect. There are some bugs in the code and the distributions from it doesn't match with randomize_undirected_signed method of BCT. I'll have a look at this but it should be noted.

**Comment by AdamLiberda** [comment]
We'll re-run these test and use the BCT as ground truth.

**Comment by TheoBerglin** [comment]
All tests are done. Closing
