### ISSUE TITLE
distribute weights

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#175]
A function that given a weighted matrix and a new connection matrix can distribute the weights so that the strength and weight distribution of the graph is preserved. This is the BCT code

**Comment by TheoBerglin** [comment]
We need to understand the differences between undirected and directed. Maybe they can use the same logic some how which would be nice.

**Comment by TheoBerglin** [comment]
Clean up the code aswell

**Comment by AdamLiberda** [comment]
Merged into dev. Closing
