### ISSUE TITLE
Main randomize function

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#176]
A main randomize function. Pseudo-code 

`rA = randomize(A, type)`
`Ac = sign(A); %Connections only`
`if is_directed(type)`
`connections = rand_gio_BD(Ac);`
`else`
`connections = rand_gio_BU(Ac);`
`end`
`if is_weighted(type)`
`rA = distribute_weights(A, connections);`
`else`
`rA = connections;`
`end`

**Comment by AdamLiberda** [comment]
Merged, closing
