### ISSUE TITLE
Method for type check with Graph object as input

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#20]
These methods should be like the static methods taking TYPE as input but take a Graph object G as input. 

I guess these can be class methods, ie called by g.is_binary() etc?

**Comment by giovannivolpe** [comment]
I'm not sure in MatLab is possible to have multiple methods its the same name. Anyways let's discuss it in person.

**Comment by TheoBerglin** [comment]
I think this is already implemented in all graph objects. What isn't implemented is positive/negative
