### ISSUE TITLE
Clustering coefficient calculations

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#26]
Clustering coefficient of a node is defined as the fraction of triangles around the node (the fraction of node's neighbors that are neighbors of each other). Clustering coefficient of the graph is defined as the average of the clustering coefficients of all nodes in the graph.

### Binary graphs
- [x] Clustering coefficient of a node undirected
- [x] Clustering coefficient of a node directed

### Weighted graphs
- [x] Clustering coefficient of a node undirected
- [x] Clustering coefficient of a node directed

### Negative graphs
- [x] Clustering coefficient of a node undirected
- [x] Clustering coefficient of a node directed

### Clustering coefficient of the graphs

- [x] Clustering coefficient of graph

### Test functions
- [x] Cluster coefficient node

- [x] Cluster coefficient graph

**Comment by TheoBerglin** [comment]
Negative directed to be implemented. Combination of negative undirected and binary directed? I think it's a valid solution but need to find reference in the literature

**Comment by TheoBerglin** [comment]
Negative directed implemented. Need som graphs to test this on

**Comment by TheoBerglin** [comment]
What's the difference between transistivity and clustering coefficient?

**Comment by AdamLiberda** [comment]
Merged, closing
