### ISSUE TITLE
Local efficiency calculations

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#32]
The local efficiency of a node is the global efficiency calculated on the subgraph created by the neighbours of the node and is related to the clustering coefficient.

- [x]  Test function local efficiency of node
- [x]  Local efficiency of node calculations

- [x]  Test function local efficiency of graph
- [x]  Local efficiency of graph calculations

**Comment by AdamLiberda** [comment]
@mitemijalkov : We need to double-check in the global efficiency if we average the results correctly.

**Comment by AdamLiberda** [comment]
Merged, closing
