### ISSUE TITLE
Betweenness calculations

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#33]
Betweenness centrality of a node is defined as the fraction of all shortest paths in a graph G that contain that node. Nodes that have high value of betweenness centrality participate in a large number of shortest paths. Function should normalize the result to be in [0, 1] given a boolean.

- [x] Test function betweenness 
- [x]  Betweenness calculations

**Comment by TheoBerglin** [comment]
Done with implementation and test function for binary directed and undirected matrix

**Comment by AdamLiberda** [comment]
Merged into develop. Closing
