### ISSUE TITLE
Transitivity calculations

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#36]
Transitivity of a graph is defined as the fraction of triangles to triplets in a graph.

### Binary undirected
- [x] Write test function 
- [x] Implement transitivity calculation

### Binary directed
- [x] Write test function 
- [x] Implement transitivity calculation

### Weighted undirected
- [x] Write test function 
- [x] Implement transitivity calculation

### Weighted directed
- [x] Write test function 
- [x] Implement transitivity calculation

### Negative weighted 
How do we handle this?

My idea is to handle it similarly to positive weighted. If one of the two connections is negative we have a negative triplet. If both of the triplets are negative or positive we have a positive triplet

**Comment by TheoBerglin** [comment]
Issue with directed weighted graphs...

**Comment by AdamLiberda** [comment]
Merged into master, closing.
