### ISSUE TITLE
Edgeattack calculation

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#4]
Edgeattack removes given edges from a graph. 

- [x] Test function

- [x] Edgeattack function

**Comment by giovannivolpe** [comment]
Edge and node attacks are not measures on graphs, but alters A. Let's do them after we are done with the measures.

**Comment by AdamLiberda** [comment]
Since this isn't a measure, and is already implemented in the object Graph, i don't think this issue needs any further action. Regarding the assessment how the measures change i think this handles itself since we create a new graph object so the measures will be set to the default values.
