### ISSUE TITLE
Folder for measures

### ISSUE THREAD

**Issue by giovannivolpe** [TheoBerglin/TutorialGIT#57]
I think it's be good to have a folder graph/measure where we put all measure functions.
The _test of the measure can be a subfolder of this one, while another _test folder can be in the main folder.
the overall structure would be:
\graph
\graph\measures
\graph\_test
\graph\measures\_test

The excel file (very good idea, btw) can be put into \graph\measures\_test

**Comment by AdamLiberda** [comment]
Why would we need two test folders?

**Comment by giovannivolpe** [comment]
I wrote wrongly, it should be:

\graph
\graph \ _test
\graph \ measures
\graph \ measures \ _test

There would be a test folder inside each folder for the functions contained there.
