### ISSUE TITLE
Z-score measure

### ISSUE THREAD

**Issue by AdamLiberda** [TheoBerglin/TutorialGIT#63]
The within-module degree z-score is a within-module version of degree centrality. It measures how well a node is connected to the other nodes in the same community. Needs the structure() method.

- [ ] Create test function
- [ ] Implement measure

**Comment by AdamLiberda** [comment]
For this function we need an additional argument: structure.

**Comment by giovannivolpe** [comment]
Ok, for all structural measures you can pass also a second argument. This is easy to check using MEASURE().STRUCTURAL

**Comment by AdamLiberda** [comment]
Merged into develop. Closing
