### ISSUE TITLE
Change properties of Graph object

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#68]
Instead of having the properties listed as static variables the properties should be one struct.

That is

DEGREE = 1;
        DEGREE_NAME = 'degree';
        DEGREE_NODAL = true;
        DEGREE_TXT = 'The degree of a node is the number of edges connected to the node. Connection weights are ignored in calculations.';

becomes 

DEGREE = 1;
properties(DEGREE ).DEGREE_NAME = 'degree'
properties(DEGREE ).FUNC= 'degree'
properties(DEGREE ).NODAL= true
properties(DEGREE).DEGREE_TXT = The degree of a node is the number of edges connected to the node. Connection weights are ignored in calculations.'

**Comment by giovannivolpe** [comment]
Yes, just small changes to how the structure should be written:

DEGREE = 1;
MEASURE(DEGREE ).NAME = 'degree'
MEASURE(DEGREE ).FUNCTION= 'degree'
MEASURE(DEGREE ).NODAL= true
MEASURE(DEGREE).DESCRIPTION = 'The degree of a node is the number of edges connected to the node. Connection weights are ignored in calculations.'

**Comment by TheoBerglin** [comment]
We should add another field to the structure:

MEASURE(DEGREE).REQUIRE_COMMUNITY_STRUCTURE = true;
