### ISSUE TITLE
Re-write measure() method

### ISSUE THREAD

**Issue by AdamLiberda** [TheoBerglin/TutorialGIT#70]
Since the functions are now independent and called in a different way we need to change the measure() method accordingly. 

- [x] Re-name to calculate_measure()
- [x] Add isempty() check
- [x] Change how we call the measures using the property struct
- [x] ~~Add check to see if measure is supported for graph type (measurelist())~~
- [x] Add check to see if community structure is needed
- [x] Add check to see if measure is an average
- [x] Special case for modularity

**Comment by giovannivolpe** [comment]
Yes, but this should be done after closing issue #68
