### ISSUE TITLE
Add getter for community structure

### ISSUE THREAD

**Issue by AdamLiberda** [TheoBerglin/TutorialGIT#75]
Add 

- [x] get_community_structure that checks if a community_structure has been calculated by checking the property

**Comment by giovannivolpe** [comment]
This function should calculate the community structure if it as not been calculated before,
and there should be another method to reset the community structure

**Comment by AdamLiberda** [comment]
We're thinking that this function will check whether a community structure has been calculated. If yes, it will return some info, if no, it will call the set_community_structure (issue #77 ), where the community structure is reset and calculated using calculate_structure().
