### ISSUE TITLE
Symmetric graphs check

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#76]
Add check for handling non symmetric structures as input to the Graph undirected constructor.
Consider the edges 1 and 2 representing the connections i->j and j->i.

If 1 or 2 has a value or both have value but they differ, either do one of the following:

Maximum value of 1 and 2
Minimum value of 1 and 2
Sum of value 1 and 2
Average of value 1 and 2

Which one is default? 

Should be able to choose the settings in the constructor.

**Comment by giovannivolpe** [comment]
let's use "Average of value 1 and 2" as default

**Comment by AdamLiberda** [comment]
Merged, closing
