### ISSUE TITLE
Weighted negative constructor check

### ISSUE THREAD

**Issue by TheoBerglin** [TheoBerglin/TutorialGIT#79]
Check if any values of the adjacency matrix of the constructor are negative. In this case they can be handled either as:

Set to 0.
Set to absolute value.

We need to decide which one is default.

Should add the option of how to handle this in the constructure of the graph object.

**Comment by giovannivolpe** [comment]
Let's use "Set to 0." as default

**Comment by AdamLiberda** [comment]
Binary graphs already handled in binarize method (issue #94 )

**Comment by AdamLiberda** [comment]
Merged into develop. Closing
