### ISSUE TITLE
Nodeattack calculations

### ISSUE THREAD

**Issue by AdamLiberda** [TheoBerglin/TutorialGIT#81]
- [x] Create test function
- [x] Implement measure

**Comment by giovannivolpe** [comment]
Just a small comment, this is not a measure, it should be separate function in the object Graph

**Comment by mitemijalkov** [comment]
Please also keep in mind that after executing the node attack, we need to asses how the measures change and statistical significance of that change.

**Comment by AdamLiberda** [comment]
Since this isn't a measure, and is already implemented in the object Graph, i don't think this issue needs any further action. Regarding the assessment how the measures change i think this handles itself since we create a new graph object so the measures will be set to the default values.

**Comment by mitemijalkov** [comment]
What I meant was that executing node attack by itself does not tell us any important information. We should assess how that change affects the graph. While the node attack at this moment works, I think it provides incomplete information and we should discuss how to implement that one. Additionally, we should implement random and targeted attacks and allow for different number of nodes to be removed. Not completely sure and we should discuss this, but I think edge attack is also important.
